/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_keyvault_free: (a: number, b: number) => void;
export const __wbg_get_keyvault_sphincs_plus_variant: (a: number) => number;
export const __wbg_set_keyvault_sphincs_plus_variant: (a: number, b: number) => void;
export const keyvault_new: (a: number) => number;
export const keyvault_clear_database: () => any;
export const keyvault_get_all_sphincs_pub: () => any;
export const keyvault_init_seed_phrase: (a: any) => any;
export const keyvault_gen_new_key_pair: (a: number, b: any) => any;
export const keyvault_import_seed_phrase: (a: any, b: any) => any;
export const keyvault_export_seed_phrase: (a: any) => any;
export const keyvault_sign: (a: number, b: any, c: number, d: number, e: any) => any;
export const keyvault_gen_account_batch: (a: number, b: any, c: number, d: number) => any;
export const keyvault_recover_accounts: (a: number, b: any, c: number) => any;
export const __wbg_util_free: (a: number, b: number) => void;
export const util_get_ckb_tx_message_all: (a: any) => [number, number, number];
export const util_password_checker: (a: any) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure80_externref_shim_multivalue_shim: (a: number, b: number, c: any) => [number, number];
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2b93dcc0cdfb007d: (a: number, b: number) => void;
export const closure40_externref_shim: (a: number, b: number, c: any) => void;
export const closure48_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
